name: Install and Configure Kops
on:
  push:
    branches:
      - develop
env:
  CREDENTIAL_CONTENT: ${{ secrets.KOPS_GOOGLE_CREDENTIALS }}
  GOOGLE_APPLICATION_CREDENTIALS: "gcp.json"
  KOPS_STATE_STORE: ${{ secrets.KOPS_STATE_STORE }}
  KOPS_CLUSTER_NAME: ${{ vars.KOPS_CLUSTER_NAME }}
  KUBECONFIG: "$kubeconfig.yaml"
  KOPS_VERSION: "v1.27.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create credentials file
        run: echo ${CREDENTIAL_CONTENT} > ${GOOGLE_APPLICATION_CREDENTIALS} 
      - name: install kops
        run: |
          mkdir -p github-actions/bin
          curl -Lo github-actions/bin/kops https://github.com/kubernetes/kops/releases/download/${KOPS_VERSION}/kops-linux-amd64
          chmod +x github-actions/bin/kops
          echo "$GITHUB_WORKSPACE/github-actions/bin" >> $GITHUB_PATH
      - name: Export Kubernetes Configuration
        run: kops export kubeconfig --admin -v 12
      - name: print the config
        run: cat $KUBECONFIG
